### ISSUE TITLE
installing this package gives me no module named

### ISSUE THREAD

**Issue by Goddard** [conda-forge/moviepy-feedstock#1]
python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moviepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'moviepy'
>>> exit()

**Comment by Goddard** [comment]
install with pip it is found

**Comment by jakirkham** [comment]
Could you please share the results of `conda env export` in the environment where you can reproduce this issue?

**Comment by Goddard** [comment]
name: root
channels:
- loopbio
- conda-forge
- defaults
dependencies:
- astropy=2.0.1=np113py36_1
- blas=1.1=openblas
- bottleneck=1.2.1=np113py36_0
- bzip2=1.0.6=1
- cairo=1.14.6=4
- conda=4.3.27=py36_0
- conda-env=2.6.0=0
- decorator=4.0.11=py36_0
- ffmpeg=3.2.4=1
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- graphviz=2.38.0=4
- h5py=2.7.0=np113py36_1
- harfbuzz=1.3.4=2
- hdf5=1.8.18=0
- icu=58.1=1
- imageio=2.1.2=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipywidgets=7.0.1=py_2
- jasper=1.900.1=4
- jpeg=9b=0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libogg=1.3.2=0
- libtiff=4.0.6=7
- libvorbis=1.3.5=0
- libwebp=0.5.2=7
- matplotlib=2.0.2=py36_2
- moviepy=0.2.3.2=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- notebook=5.1.0=py36_0
- numexpr=2.6.2=np113py36_0
- numpy=1.13.1=py36_blas_openblas_200
- openblas=0.2.19=2
- opencv=3.3.0=py36_blas_openblas_200
- pandoc=1.19.2=0
- pango=1.40.3=3
- pillow=4.2.1=py36_0
- pytables=3.4.2=np113py36_1
- pywavelets=0.5.2=np113py36_0
- qt=5.6.2=3
- qtconsole=4.3.1=py36_0
- scikit-image=0.13.0=py36_1
- scikit-learn=0.19.0=py36_blas_openblas_201
- scipy=0.19.1=py36_blas_openblas_202
- statsmodels=0.8.0=np113py36_0
- tqdm=4.11.2=py36_0
- widgetsnbextension=3.0.3=py36_2
- x264=20131217=3
- _license=1.1=py36_1
- alabaster=0.7.10=py36_0
- anaconda-client=1.6.3=py36_0
- anaconda=custom=py36_0
- anaconda-navigator=1.6.4=py36_0
- anaconda-project=0.6.0=py36_0
- asn1crypto=0.22.0=py36_0
- astroid=1.5.3=py36_0
- babel=2.5.0=py36_0
- backports=1.0=py36_0
- backports.weakref=1.0rc1=py36_0
- beautifulsoup4=4.6.0=py36_0
- bitarray=0.8.1=py36_0
- bkcharts=0.2=py36_0
- blaze=0.10.1=py36_0
- bleach=1.5.0=py36_0
- bokeh=0.12.7=py36_0
- boto=2.48.0=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- cloudpickle=0.4.0=py36_0
- clyent=1.2.2=py36_0
- colorama=0.3.9=py36_0
- contextlib2=0.5.5=py36_0
- cryptography=1.8.1=py36_0
- cudatoolkit=8.0=1
- cudnn=6.0.21=cuda8.0_0
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- cython=0.26=py36_0
- cytoolz=0.8.2=py36_0
- dask=0.15.2=py36_0
- datashape=0.5.4=py36_0
- dbus=1.10.20=0
- distributed=1.18.1=py36_0
- docutils=0.14=py36_0
- entrypoints=0.2.3=py36_0
- et_xmlfile=1.0.1=py36_0
- expat=2.1.0=0
- fastcache=1.0.2=py36_1
- flask=0.12.2=py36_0
- flask-cors=3.0.3=py36_0
- get_terminal_size=1.0.0=py36_0
- gevent=1.2.2=py36_0
- greenlet=0.4.12=py36_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- heapdict=1.0.0=py36_1
- html5lib=0.9999999=py36_0
- idna=2.6=py36_0
- imagesize=0.7.1=py36_0
- ipython_genutils=0.2.0=py36_0
- isort=4.2.15=py36_0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jdcal=1.3=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jsonschema=2.6.0=py36_0
- lazy-object-proxy=1.3.1=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libprotobuf=3.2.0=0
- libsodium=1.0.10=0
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.19.0=py36_0
- locket=0.2.0=py36_1
- lxml=3.8.0=py36_0
- lzo=2.06=0
- mako=1.0.6=py36_0
- markdown=2.6.9=py36_0
- markupsafe=1.0=py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py36_3
- mpmath=0.19=py36_1
- msgpack-python=0.4.8=py36_0
- multipledispatch=0.4.9=py36_0
- navigator-updater=0.1.0=py36_0
- networkx=1.11=py36_0
- nltk=3.2.4=py36_0
- nose=1.3.7=py36_1
- numba=0.34.0=np113py36_0
- numpydoc=0.7.0=py36_0
- odo=0.5.1=py36_0
- olefile=0.44=py36_0
- openpyxl=2.4.8=py36_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- pandas=0.20.3=py36_0
- pandocfilters=1.4.2=py36_0
- partd=0.3.8=py36_0
- path.py=10.3.1=py36_0
- pathlib2=2.3.0=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=1
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- ply=3.10=py36_0
- prompt_toolkit=1.0.15=py36_0
- protobuf=3.2.0=py36_0
- psutil=5.2.2=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.4.34=py36_0
- pycodestyle=2.3.1=py36_0
- pycosat=0.6.2=py36_0
- pycparser=2.18=py36_0
- pycrypto=2.6.1=py36_6
- pycurl=7.43.0=py36_2
- pyflakes=1.6.0=py36_0
- pygments=2.2.0=py36_0
- pygpu=0.6.9=py36_0
- pylint=1.7.2=py36_0
- pyodbc=4.0.17=py36_0
- pyopenssl=17.0.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.2.1=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qtawesome=0.4.4=py36_0
- qtpy=1.3.1=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- rope=0.9.4=py36_1
- ruamel_yaml=0.11.14=py36_1
- seaborn=0.8=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sortedcollections=0.5.3=py36_0
- sortedcontainers=1.5.7=py36_0
- sphinx=1.6.3=py36_0
- sphinxcontrib=1.0=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=0
- sympy=1.1.1=py36_0
- tblib=1.3.2=py36_0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- theano=0.9.0=py36_0
- tk=8.5.18=0
- toolz=0.8.2=py36_0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- unicodecsv=0.14.1=py36_0
- unixodbc=2.3.4=0
- wcwidth=0.1.7=py36_0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- wrapt=1.10.11=py36_0
- xlrd=1.1.0=py36_0
- xlsxwriter=0.9.8=py36_0
- xlwt=1.3.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zict=0.1.2=py36_0
- zlib=1.2.11=0
- gtk2-feature=1.0=1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - bottle==0.12.13
  - conan==0.27.0
  - distro==1.0.4
  - et-xmlfile==1.0.1
  - fasteners==0.14.1
  - future==0.16.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - keras==2.0.8
  - monotonic==1.3
  - node-semver==0.2.0
  - patch==1.16
  - pluginbase==0.5
  - prompt-toolkit==1.0.15
  - pyjwt==1.5.3
  - rope-py3k==0.9.4.post1
  - tables==3.4.2
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.5
prefix: /home/irenicus/anaconda3

**Comment by jakirkham** [comment]
So just created a simplified environment and am unable to reproduce this. Could you please try with this environment and see if the issue goes away for you? Here are some [docs]( https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file ) on how to do this.

Environment

<details>

```yaml
# filename: environment.yml
name: test
channels:
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- decorator=4.0.11=py36_0
- ffmpeg=3.2.4=1
- freetype=2.7=1
- imageio=2.1.2=py36_0
- jpeg=9b=1
- libiconv=1.14=4
- libpng=1.6.28=1
- libtiff=4.0.7=0
- moviepy=0.2.3.2=py36_0
- ncurses=5.9=10
- numpy=1.13.3=py36_blas_openblas_200
- olefile=0.44=py36_0
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pillow=4.3.0=py36_0
- pip=9.0.1=py36_0
- python=3.6.3=0
- readline=6.2=0
- setuptools=36.3.0=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- tqdm=4.11.2=py36_0
- wheel=0.30.0=py_1
- x264=20131217=3
- xz=5.2.3=0
- zlib=1.2.8=3
- libgfortran=3.0.0=1
```

</details>

**Comment by jakirkham** [comment]
Also can you please tell me the results of `which python` just to humor me. 😄

**Comment by Goddard** [comment]
ResolvePackageNotFound:
  - libgfortran 3.0.0 0

**Comment by Goddard** [comment]
I changed it to 
libgfortran 3.0.0=1

which python
/home/user/anaconda3/envs/test/bin/python

python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import moveipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named moveipy
>>>

Here is the result from a notebook.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-3882ad75caa2> in <module>()
      1 # Import everything needed to edit/save/watch video clips
----> 2 from moviepy.editor import VideoFileClip
      3 from IPython.display import HTML

ModuleNotFoundError: No module named 'moviepy'

**Comment by jakirkham** [comment]
Sorry that was on my Mac. Forgot you were on Linux. Update the environment file above. Worked for me on Linux. Can you please retry with the edited environment file (the comment should say Edited on it)?

**Comment by Goddard** [comment]
yeah look above same thing

**Comment by jakirkham** [comment]
Can you please run `ls /home/user/anaconda3/envs/test/lib/python3.6/site-packages/`?

**Comment by Goddard** [comment]
Above ls didn't work, but this did
ls /home/user/anaconda3/envs/test/lib/python2.7/site-packages/

certifi                              imageio-2.1.2-py2.7.egg-info    OleFileIO_PL.pyc             setuptools-36.3.0-py2.7.egg-info
certifi-2017.07.27.1-py2.7.egg-info  moviepy                         PIL                          tests
decorator-4.0.11-py2.7.egg-info      moviepy-0.2.3.2-py2.7.egg-info  Pillow-4.3.0-py2.7.egg-info  tqdm
decorator.py                         numpy                           pip                          tqdm-4.11.2-py2.7.egg-info
decorator.pyc                        numpy-1.13.2-py2.7.egg-info     pip-9.0.1-py2.7.egg-info     wheel
easy_install.py                      olefile                         pkg_resources                wheel-0.30.0-py3.6.egg-info
easy_install.pyc                     olefile-0.44-py2.7.egg-info     README
imageio                              OleFileIO_PL.py                 setuptools

**Comment by jakirkham** [comment]
Would remove the environment and recreate it with the environment file above. Looks like it has some Python 2.7 and 3.6 stuff in there at the same time, which is problematic.

**Comment by jakirkham** [comment]
Were you able to resolve this, @Goddard?

**Comment by Goddard** [comment]
I just had so many issues I just used opencv instead.

**Comment by jakirkham** [comment]
Alright, am going to close out then.

Would expect that there is no issue if starting with a fresh environment (as the old one appeared to have gotten contaminated somehow). Did the same myself today. However if you are able to reproduce an issue in a minimal environment, would be happy to reopen and discuss. :)

**Comment by chysam** [comment]
i have the same problem
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Python\Python36-32\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python\Python36-32\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "C:\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'channels'
